export interface User {
    "login": string,
    "avatar_url": string,
    "html_url": string,
    "organizations_url": string,
    "name": string,
    "company": null,
    "blog": string,
    "location": string,
    "email": string,
    "hireable": boolean,
    "public_repos": number,
    "followers": number,
    "following": number,
    "created_at": string,
}